<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\CourseRecord;
use app\models\LessonRecord;

class CourseController extends Controller
{

    //вызов списка курсов - главная страница
    public function actionIndex() //список курсов (пользователя)
    {
        $model = CourseRecord::find()->all();
        return $this->render('index',['courses'=>$model]) ;// TODO: Change the autogenerated stub
    }

    //вызов курса со списком уроков
    public  function  actionViewcourse($id)
    {
        return $this->render('viewcourse', [
            'model' => $this->findCourse($id),
        ]);
    }


    //вызов представления для урока
    public  function  actionViewlesson($id)
    {
        return $this->render('viewlesson_step', [
            'model' => $this->findLesson($id),
        ]);
    }


//поиск курсов
    protected function findCourse($id)
    {
        if (($model = CourseRecord::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    //поиск урока по id
    protected function findLesson($id)
    {
        if (($model = LessonRecord::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public  function  actionBlock(){
        $this->render('part\block');
    }


}