<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\CourseRecord;

class CourseController extends Controller
{

    public function actionIndex() //список курсов (пользователя)
    {
        $model = CourseRecord::find()->all();
        return $this->render('index',['courses'=>$model]) ;// TODO: Change the autogenerated stub
    }

    public  function  actionViewcourse($id)
    {
        return $this->render('viewcourse', [
            'model' => $this->findCourse($id),
        ]);
    }
//поиск курсов
    protected function findCourse($id)
    {
        if (($model = CourseRecord::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


}